// Auto-generated from IPU_CET_College_Predictor_2025.xlsx
// Last Round (Round 3) cutoffs for 2025-26

export type CetCourseGroup = "BBA" | "BCA" | "Law" | "B.Com" | "MCA" | "MBA";

export type CetCutoffEntry = {
  college: string;
  course: string;
  courseGroup: CetCourseGroup;
  shift: string;
  category: "GEN" | "SC" | "OBC";
  region: "delhi" | "outside_delhi";
  openRank: number;
  closeRank: number;
  remarks: string;
};

export const cetCutoffData: CetCutoffEntry[] = 
[
  {
    "college": "University School of Management Studies (USMS), GGSIPU Campus, Dwarka",
    "course": "BBA",
    "courseGroup": "BBA",
    "shift": "Morning",
    "category": "GEN",
    "region": "delhi",
    "openRank": 2,
    "closeRank": 178,
    "remarks": "Best BBA – Uni campus"
  },
  {
    "college": "University School of Management Studies (USMS), GGSIPU Campus, Dwarka",
    "course": "BBA",
    "courseGroup": "BBA",
    "shift": "Morning",
    "category": "GEN",
    "region": "outside_delhi",
    "openRank": 22,
    "closeRank": 274,
    "remarks": ""
  },
  {
    "college": "Vivekananda Institute of Professional Studies (VIPS), Pitampura",
    "course": "BBA",
    "courseGroup": "BBA",
    "shift": "Shift I",
    "category": "GEN",
    "region": "delhi",
    "openRank": 1,
    "closeRank": 571,
    "remarks": "Top private BBA college"
  },
  {
    "college": "Vivekananda Institute of Professional Studies (VIPS), Pitampura",
    "course": "BBA",
    "courseGroup": "BBA",
    "shift": "Shift II",
    "category": "GEN",
    "region": "delhi",
    "openRank": 370,
    "closeRank": 1171,
    "remarks": ""
  },
  {
    "college": "Vivekananda Institute of Professional Studies (VIPS), Pitampura",
    "course": "BBA",
    "courseGroup": "BBA",
    "shift": "Shift I",
    "category": "GEN",
    "region": "outside_delhi",
    "openRank": 229,
    "closeRank": 558,
    "remarks": ""
  },
  {
    "college": "Maharaja Surajmal Institute (MSI), Janakpuri",
    "course": "BBA",
    "courseGroup": "BBA",
    "shift": "Shift I",
    "category": "GEN",
    "region": "delhi",
    "openRank": 49,
    "closeRank": 961,
    "remarks": ""
  },
  {
    "college": "Maharaja Surajmal Institute (MSI), Janakpuri",
    "course": "BBA",
    "courseGroup": "BBA",
    "shift": "Shift II",
    "category": "GEN",
    "region": "delhi",
    "openRank": 473,
    "closeRank": 1855,
    "remarks": ""
  },
  {
    "college": "Maharaja Surajmal Institute (MSI), Janakpuri",
    "course": "BBA [Banking & Insurance]",
    "courseGroup": "BBA",
    "shift": "Shift I",
    "category": "GEN",
    "region": "delhi",
    "openRank": 101,
    "closeRank": 1522,
    "remarks": ""
  },
  {
    "college": "Maharaja Surajmal Institute (MSI), Janakpuri",
    "course": "BBA [Banking & Insurance]",
    "courseGroup": "BBA",
    "shift": "Shift II",
    "category": "GEN",
    "region": "delhi",
    "openRank": 603,
    "closeRank": 2170,
    "remarks": ""
  },
  {
    "college": "Maharaja Surajmal Institute (MSI), Janakpuri",
    "course": "BBA",
    "courseGroup": "BBA",
    "shift": "Shift I",
    "category": "GEN",
    "region": "outside_delhi",
    "openRank": 91,
    "closeRank": 397,
    "remarks": ""
  },
  {
    "college": "Maharaja Surajmal Institute (MSI), Janakpuri",
    "course": "BBA",
    "courseGroup": "BBA",
    "shift": "Shift II",
    "category": "GEN",
    "region": "outside_delhi",
    "openRank": 447,
    "closeRank": 937,
    "remarks": ""
  },
  {
    "college": "Maharaja Agrasen Institute of Management Studies (MAIMS), Rohini",
    "course": "BBA",
    "courseGroup": "BBA",
    "shift": "Shift I",
    "category": "GEN",
    "region": "delhi",
    "openRank": 69,
    "closeRank": 1919,
    "remarks": ""
  },
  {
    "college": "Maharaja Agrasen Institute of Management Studies (MAIMS), Rohini",
    "course": "BBA",
    "courseGroup": "BBA",
    "shift": "Shift II",
    "category": "GEN",
    "region": "delhi",
    "openRank": 920,
    "closeRank": 2587,
    "remarks": ""
  },
  {
    "college": "Maharaja Agrasen Institute of Management Studies (MAIMS), Rohini",
    "course": "BBA",
    "courseGroup": "BBA",
    "shift": "Shift I",
    "category": "GEN",
    "region": "outside_delhi",
    "openRank": 233,
    "closeRank": 1041,
    "remarks": ""
  },
  {
    "college": "Maharaja Agrasen Institute of Technology (MAIT), Rohini",
    "course": "BBA",
    "courseGroup": "BBA",
    "shift": "Morning",
    "category": "GEN",
    "region": "delhi",
    "openRank": 434,
    "closeRank": 2751,
    "remarks": ""
  },
  {
    "college": "Maharaja Agrasen Institute of Technology (MAIT), Rohini",
    "course": "BBA",
    "courseGroup": "BBA",
    "shift": "Morning",
    "category": "GEN",
    "region": "outside_delhi",
    "openRank": 592,
    "closeRank": 1381,
    "remarks": ""
  },
  {
    "college": "Jagan Institute of Management Studies (JIMS), Rohini Sector-5",
    "course": "BBA",
    "courseGroup": "BBA",
    "shift": "Shift I",
    "category": "GEN",
    "region": "delhi",
    "openRank": 1117,
    "closeRank": 2534,
    "remarks": ""
  },
  {
    "college": "Jagan Institute of Management Studies (JIMS), Rohini Sector-5",
    "course": "BBA",
    "courseGroup": "BBA",
    "shift": "Shift II",
    "category": "GEN",
    "region": "delhi",
    "openRank": 987,
    "closeRank": 1525,
    "remarks": ""
  },
  {
    "college": "Jagan Institute of Management Studies (JIMS), Rohini Sector-5",
    "course": "BBA",
    "courseGroup": "BBA",
    "shift": "Shift I",
    "category": "GEN",
    "region": "outside_delhi",
    "openRank": 908,
    "closeRank": 1256,
    "remarks": ""
  },
  {
    "college": "Jagannath International Management School (JIMS), Vasant Kunj",
    "course": "BBA",
    "courseGroup": "BBA",
    "shift": "Shift I",
    "category": "GEN",
    "region": "delhi",
    "openRank": 1217,
    "closeRank": 3455,
    "remarks": ""
  },
  {
    "college": "Jagannath International Management School (JIMS), Vasant Kunj",
    "course": "BBA",
    "courseGroup": "BBA",
    "shift": "Shift II",
    "category": "GEN",
    "region": "delhi",
    "openRank": 2298,
    "closeRank": 4236,
    "remarks": ""
  },
  {
    "college": "Jagannath International Management School (JIMS), Vasant Kunj",
    "course": "BBA",
    "courseGroup": "BBA",
    "shift": "Shift I",
    "category": "GEN",
    "region": "outside_delhi",
    "openRank": 344,
    "closeRank": 1563,
    "remarks": ""
  },
  {
    "college": "Institute of Innovation in Technology & Management (IITM), Janakpuri",
    "course": "BBA",
    "courseGroup": "BBA",
    "shift": "Shift I",
    "category": "GEN",
    "region": "delhi",
    "openRank": 2140,
    "closeRank": 6927,
    "remarks": ""
  },
  {
    "college": "Institute of Innovation in Technology & Management (IITM), Janakpuri",
    "course": "BBA",
    "courseGroup": "BBA",
    "shift": "Shift II",
    "category": "GEN",
    "region": "delhi",
    "openRank": 2897,
    "closeRank": 9442,
    "remarks": ""
  },
  {
    "college": "Institute of Innovation in Technology & Management (IITM), Janakpuri",
    "course": "BBA",
    "courseGroup": "BBA",
    "shift": "Shift I",
    "category": "GEN",
    "region": "outside_delhi",
    "openRank": 1758,
    "closeRank": 3989,
    "remarks": ""
  },
  {
    "college": "Bhagwan Parshuram Institute of Technology (BPIT), Rohini",
    "course": "BBA",
    "courseGroup": "BBA",
    "shift": "Shift I",
    "category": "GEN",
    "region": "delhi",
    "openRank": 1802,
    "closeRank": 4546,
    "remarks": ""
  },
  {
    "college": "Bhagwan Parshuram Institute of Technology (BPIT), Rohini",
    "course": "BBA",
    "courseGroup": "BBA",
    "shift": "Shift II",
    "category": "GEN",
    "region": "delhi",
    "openRank": 2928,
    "closeRank": 6216,
    "remarks": ""
  },
  {
    "college": "Bhagwan Parshuram Institute of Technology (BPIT), Rohini",
    "course": "BBA",
    "courseGroup": "BBA",
    "shift": "Shift I",
    "category": "GEN",
    "region": "outside_delhi",
    "openRank": 1713,
    "closeRank": 2760,
    "remarks": ""
  },
  {
    "college": "Trinity Institute of Professional Studies, Dwarka",
    "course": "BBA",
    "courseGroup": "BBA",
    "shift": "Shift I",
    "category": "GEN",
    "region": "delhi",
    "openRank": 2350,
    "closeRank": 7793,
    "remarks": ""
  },
  {
    "college": "Trinity Institute of Professional Studies, Dwarka",
    "course": "BBA",
    "courseGroup": "BBA",
    "shift": "Shift II",
    "category": "GEN",
    "region": "delhi",
    "openRank": 5055,
    "closeRank": 12025,
    "remarks": ""
  },
  {
    "college": "Trinity Institute of Professional Studies, Dwarka",
    "course": "BBA",
    "courseGroup": "BBA",
    "shift": "Shift I",
    "category": "GEN",
    "region": "outside_delhi",
    "openRank": 1123,
    "closeRank": 3222,
    "remarks": ""
  },
  {
    "college": "Rukmini Devi Institute of Advanced Studies (RDIAS), Rohini",
    "course": "BBA",
    "courseGroup": "BBA",
    "shift": "Shift I",
    "category": "GEN",
    "region": "delhi",
    "openRank": 2317,
    "closeRank": 7686,
    "remarks": ""
  },
  {
    "college": "Rukmini Devi Institute of Advanced Studies (RDIAS), Rohini",
    "course": "BBA",
    "courseGroup": "BBA",
    "shift": "Shift I",
    "category": "GEN",
    "region": "outside_delhi",
    "openRank": 1613,
    "closeRank": 3881,
    "remarks": ""
  },
  {
    "college": "Tecnia Institute of Advanced Studies, Rohini",
    "course": "BBA",
    "courseGroup": "BBA",
    "shift": "Shift I",
    "category": "GEN",
    "region": "delhi",
    "openRank": 3094,
    "closeRank": 11263,
    "remarks": ""
  },
  {
    "college": "Tecnia Institute of Advanced Studies, Rohini",
    "course": "BBA",
    "courseGroup": "BBA",
    "shift": "Shift I",
    "category": "GEN",
    "region": "outside_delhi",
    "openRank": 2423,
    "closeRank": 7316,
    "remarks": ""
  },
  {
    "college": "Gitarattan International Business School (GIBS), Rohini",
    "course": "BBA",
    "courseGroup": "BBA",
    "shift": "Shift I",
    "category": "GEN",
    "region": "delhi",
    "openRank": 3029,
    "closeRank": 14087,
    "remarks": ""
  },
  {
    "college": "Gitarattan International Business School (GIBS), Rohini",
    "course": "BBA",
    "courseGroup": "BBA",
    "shift": "Shift II",
    "category": "GEN",
    "region": "delhi",
    "openRank": 5010,
    "closeRank": 14856,
    "remarks": ""
  },
  {
    "college": "Gitarattan International Business School (GIBS), Rohini",
    "course": "BBA",
    "courseGroup": "BBA",
    "shift": "Shift I",
    "category": "GEN",
    "region": "outside_delhi",
    "openRank": 2005,
    "closeRank": 8557,
    "remarks": ""
  },
  {
    "college": "Gitarattan International Business School (GIBS), Rohini",
    "course": "BBA [5yr MBA Integrated]",
    "courseGroup": "BBA",
    "shift": "Morning",
    "category": "GEN",
    "region": "delhi",
    "openRank": 1371,
    "closeRank": 14937,
    "remarks": "5yr BBA-MBA integrated"
  },
  {
    "college": "New Delhi Institute of Management (NDIM), Tughlakabad",
    "course": "BBA",
    "courseGroup": "BBA",
    "shift": "Shift I",
    "category": "GEN",
    "region": "delhi",
    "openRank": 2930,
    "closeRank": 14950,
    "remarks": ""
  },
  {
    "college": "New Delhi Institute of Management (NDIM), Tughlakabad",
    "course": "BBA",
    "courseGroup": "BBA",
    "shift": "Shift I",
    "category": "GEN",
    "region": "outside_delhi",
    "openRank": 1186,
    "closeRank": 5705,
    "remarks": ""
  },
  {
    "college": "Institute of Information Technology & Management (IITM-JP), Janakpuri",
    "course": "BBA",
    "courseGroup": "BBA",
    "shift": "Shift I",
    "category": "GEN",
    "region": "delhi",
    "openRank": 2112,
    "closeRank": 4724,
    "remarks": ""
  },
  {
    "college": "Institute of Information Technology & Management (IITM-JP), Janakpuri",
    "course": "BBA",
    "courseGroup": "BBA",
    "shift": "Shift II",
    "category": "GEN",
    "region": "delhi",
    "openRank": 2569,
    "closeRank": 6297,
    "remarks": ""
  },
  {
    "college": "Banarsidas Chandiwala Institute of Professional Studies (BCIPS), Dwarka",
    "course": "BBA",
    "courseGroup": "BBA",
    "shift": "Shift I",
    "category": "GEN",
    "region": "delhi",
    "openRank": 3495,
    "closeRank": 11065,
    "remarks": ""
  },
  {
    "college": "Banarsidas Chandiwala Institute of Professional Studies (BCIPS), Dwarka",
    "course": "BBA",
    "courseGroup": "BBA",
    "shift": "Shift II",
    "category": "GEN",
    "region": "delhi",
    "openRank": 5734,
    "closeRank": 14671,
    "remarks": ""
  },
  {
    "college": "Sirifort Institute of Management Studies, Rohini",
    "course": "BBA",
    "courseGroup": "BBA",
    "shift": "Shift I",
    "category": "GEN",
    "region": "delhi",
    "openRank": 3142,
    "closeRank": 14960,
    "remarks": ""
  },
  {
    "college": "Fairfield Institute of Management & Technology (FIMT), Kapashera",
    "course": "BBA",
    "courseGroup": "BBA",
    "shift": "Shift I",
    "category": "GEN",
    "region": "delhi",
    "openRank": 7512,
    "closeRank": 14788,
    "remarks": ""
  },
  {
    "college": "Fairfield Institute of Management & Technology (FIMT), Kapashera",
    "course": "BBA",
    "courseGroup": "BBA",
    "shift": "Shift I",
    "category": "GEN",
    "region": "outside_delhi",
    "openRank": 1546,
    "closeRank": 8588,
    "remarks": ""
  },
  {
    "college": "Don Bosco Institute of Technology, Okhla",
    "course": "BBA",
    "courseGroup": "BBA",
    "shift": "Morning",
    "category": "GEN",
    "region": "delhi",
    "openRank": 3425,
    "closeRank": 14929,
    "remarks": ""
  },
  {
    "college": "Sri Guru Tegh Bahadur IMIT, GTK Road",
    "course": "BBA",
    "courseGroup": "BBA",
    "shift": "Shift I",
    "category": "GEN",
    "region": "delhi",
    "openRank": 2633,
    "closeRank": 13895,
    "remarks": ""
  },
  {
    "college": "Vivekananda Institute of Professional Studies (VIPS), Pitampura",
    "course": "BBA",
    "courseGroup": "BBA",
    "shift": "Shift I",
    "category": "SC",
    "region": "delhi",
    "openRank": 3567,
    "closeRank": 10580,
    "remarks": "SC Category"
  },
  {
    "college": "Maharaja Surajmal Institute (MSI), Janakpuri",
    "course": "BBA",
    "courseGroup": "BBA",
    "shift": "Shift I",
    "category": "SC",
    "region": "delhi",
    "openRank": 1469,
    "closeRank": 14459,
    "remarks": "SC Category"
  },
  {
    "college": "Maharaja Agrasen Institute of Management Studies (MAIMS), Rohini",
    "course": "BBA",
    "courseGroup": "BBA",
    "shift": "Shift I",
    "category": "SC",
    "region": "delhi",
    "openRank": 3470,
    "closeRank": 13612,
    "remarks": "SC Category"
  },
  {
    "college": "University School of Management Studies (USMS)",
    "course": "BBA",
    "courseGroup": "BBA",
    "shift": "Morning",
    "category": "OBC",
    "region": "delhi",
    "openRank": 185,
    "closeRank": 2305,
    "remarks": "OBC Category"
  },
  {
    "college": "Maharaja Surajmal Institute (MSI), Janakpuri",
    "course": "BCA",
    "courseGroup": "BCA",
    "shift": "Shift I",
    "category": "GEN",
    "region": "delhi",
    "openRank": 2,
    "closeRank": 305,
    "remarks": "Best private BCA"
  },
  {
    "college": "Maharaja Surajmal Institute (MSI), Janakpuri",
    "course": "BCA",
    "courseGroup": "BCA",
    "shift": "Shift II",
    "category": "GEN",
    "region": "delhi",
    "openRank": 67,
    "closeRank": 646,
    "remarks": ""
  },
  {
    "college": "Maharaja Surajmal Institute (MSI), Janakpuri",
    "course": "BCA",
    "courseGroup": "BCA",
    "shift": "Shift I",
    "category": "GEN",
    "region": "outside_delhi",
    "openRank": 11,
    "closeRank": 318,
    "remarks": ""
  },
  {
    "college": "Maharaja Surajmal Institute (MSI), Janakpuri",
    "course": "BCA",
    "courseGroup": "BCA",
    "shift": "Shift II",
    "category": "GEN",
    "region": "outside_delhi",
    "openRank": 32,
    "closeRank": 554,
    "remarks": ""
  },
  {
    "college": "Vivekananda Institute of Professional Studies (VIPS), Pitampura",
    "course": "BCA",
    "courseGroup": "BCA",
    "shift": "Shift I",
    "category": "GEN",
    "region": "delhi",
    "openRank": 17,
    "closeRank": 602,
    "remarks": ""
  },
  {
    "college": "Vivekananda Institute of Professional Studies (VIPS), Pitampura",
    "course": "BCA",
    "courseGroup": "BCA",
    "shift": "Shift II",
    "category": "GEN",
    "region": "delhi",
    "openRank": 14,
    "closeRank": 759,
    "remarks": ""
  },
  {
    "college": "Vivekananda Institute of Professional Studies (VIPS), Pitampura",
    "course": "BCA",
    "courseGroup": "BCA",
    "shift": "Shift I",
    "category": "GEN",
    "region": "outside_delhi",
    "openRank": 28,
    "closeRank": 353,
    "remarks": ""
  },
  {
    "college": "Maharaja Agrasen Institute of Management Studies (MAIMS), Rohini",
    "course": "BCA",
    "courseGroup": "BCA",
    "shift": "Morning",
    "category": "GEN",
    "region": "delhi",
    "openRank": 41,
    "closeRank": 789,
    "remarks": ""
  },
  {
    "college": "Maharaja Agrasen Institute of Management Studies (MAIMS), Rohini",
    "course": "BCA",
    "courseGroup": "BCA",
    "shift": "Morning",
    "category": "GEN",
    "region": "outside_delhi",
    "openRank": 331,
    "closeRank": 695,
    "remarks": ""
  },
  {
    "college": "Jagan Institute of Management Studies (JIMS), Rohini Sector-5",
    "course": "BCA",
    "courseGroup": "BCA",
    "shift": "Shift I",
    "category": "GEN",
    "region": "delhi",
    "openRank": 487,
    "closeRank": 898,
    "remarks": ""
  },
  {
    "college": "Jagan Institute of Management Studies (JIMS), Rohini Sector-5",
    "course": "BCA",
    "courseGroup": "BCA",
    "shift": "Shift II",
    "category": "GEN",
    "region": "delhi",
    "openRank": 592,
    "closeRank": 1083,
    "remarks": ""
  },
  {
    "college": "Jagan Institute of Management Studies (JIMS), Rohini Sector-5",
    "course": "BCA",
    "courseGroup": "BCA",
    "shift": "Shift I",
    "category": "GEN",
    "region": "outside_delhi",
    "openRank": 556,
    "closeRank": 1024,
    "remarks": ""
  },
  {
    "college": "Jagannath International Management School (JIMS), Vasant Kunj",
    "course": "BCA",
    "courseGroup": "BCA",
    "shift": "Shift I",
    "category": "GEN",
    "region": "delhi",
    "openRank": 313,
    "closeRank": 1409,
    "remarks": ""
  },
  {
    "college": "Jagannath International Management School (JIMS), Vasant Kunj",
    "course": "BCA",
    "courseGroup": "BCA",
    "shift": "Shift II",
    "category": "GEN",
    "region": "delhi",
    "openRank": 84,
    "closeRank": 2036,
    "remarks": ""
  },
  {
    "college": "Jagannath International Management School (JIMS), Vasant Kunj",
    "course": "BCA",
    "courseGroup": "BCA",
    "shift": "Shift I",
    "category": "GEN",
    "region": "outside_delhi",
    "openRank": 436,
    "closeRank": 874,
    "remarks": ""
  },
  {
    "college": "Institute of Information Technology & Management (IITM), Janakpuri",
    "course": "BCA",
    "courseGroup": "BCA",
    "shift": "Shift I",
    "category": "GEN",
    "region": "delhi",
    "openRank": 618,
    "closeRank": 1424,
    "remarks": ""
  },
  {
    "college": "Institute of Information Technology & Management (IITM), Janakpuri",
    "course": "BCA",
    "courseGroup": "BCA",
    "shift": "Shift II",
    "category": "GEN",
    "region": "delhi",
    "openRank": 798,
    "closeRank": 2011,
    "remarks": ""
  },
  {
    "college": "Institute of Information Technology & Management (IITM), Janakpuri",
    "course": "BCA",
    "courseGroup": "BCA",
    "shift": "Shift I",
    "category": "GEN",
    "region": "outside_delhi",
    "openRank": 365,
    "closeRank": 1330,
    "remarks": ""
  },
  {
    "college": "Institute of Innovation in Technology & Management (IITM-D27), Janakpuri",
    "course": "BCA",
    "courseGroup": "BCA",
    "shift": "Shift I",
    "category": "GEN",
    "region": "delhi",
    "openRank": 924,
    "closeRank": 2212,
    "remarks": ""
  },
  {
    "college": "Institute of Innovation in Technology & Management (IITM-D27), Janakpuri",
    "course": "BCA",
    "courseGroup": "BCA",
    "shift": "Shift II",
    "category": "GEN",
    "region": "delhi",
    "openRank": 1196,
    "closeRank": 2827,
    "remarks": ""
  },
  {
    "college": "Institute of Innovation in Technology & Management (IITM-D27), Janakpuri",
    "course": "BCA",
    "courseGroup": "BCA",
    "shift": "Shift I",
    "category": "GEN",
    "region": "outside_delhi",
    "openRank": 1018,
    "closeRank": 2653,
    "remarks": ""
  },
  {
    "college": "Banarsidas Chandiwala Institute of Information Technology (BCIIT), Kalkaji",
    "course": "BCA",
    "courseGroup": "BCA",
    "shift": "Morning",
    "category": "GEN",
    "region": "delhi",
    "openRank": 167,
    "closeRank": 3126,
    "remarks": ""
  },
  {
    "college": "Banarsidas Chandiwala Institute of Information Technology (BCIIT), Kalkaji",
    "course": "BCA",
    "courseGroup": "BCA",
    "shift": "Morning",
    "category": "GEN",
    "region": "outside_delhi",
    "openRank": 1300,
    "closeRank": 3610,
    "remarks": ""
  },
  {
    "college": "Don Bosco Institute of Technology, Okhla",
    "course": "BCA",
    "courseGroup": "BCA",
    "shift": "Morning",
    "category": "GEN",
    "region": "delhi",
    "openRank": 547,
    "closeRank": 4864,
    "remarks": ""
  },
  {
    "college": "Don Bosco Institute of Technology, Okhla",
    "course": "BCA",
    "courseGroup": "BCA",
    "shift": "Morning",
    "category": "GEN",
    "region": "outside_delhi",
    "openRank": 1595,
    "closeRank": 4183,
    "remarks": ""
  },
  {
    "college": "Delhi School of Professional Studies & Research (DSPSR), Rohini",
    "course": "BCA",
    "courseGroup": "BCA",
    "shift": "Morning",
    "category": "GEN",
    "region": "delhi",
    "openRank": 803,
    "closeRank": 5908,
    "remarks": ""
  },
  {
    "college": "Sri Guru Tegh Bahadur IMIT, GTK Road",
    "course": "BCA",
    "courseGroup": "BCA",
    "shift": "Shift I",
    "category": "GEN",
    "region": "delhi",
    "openRank": 723,
    "closeRank": 4825,
    "remarks": ""
  },
  {
    "college": "Trinity Institute of Professional Studies, Dwarka",
    "course": "BCA",
    "courseGroup": "BCA",
    "shift": "Shift I",
    "category": "GEN",
    "region": "delhi",
    "openRank": 946,
    "closeRank": 2769,
    "remarks": ""
  },
  {
    "college": "Trinity Institute of Professional Studies, Dwarka",
    "course": "BCA",
    "courseGroup": "BCA",
    "shift": "Shift II",
    "category": "GEN",
    "region": "delhi",
    "openRank": 2321,
    "closeRank": 3372,
    "remarks": ""
  },
  {
    "college": "Tecnia Institute of Advanced Studies, Rohini",
    "course": "BCA",
    "courseGroup": "BCA",
    "shift": "Shift I",
    "category": "GEN",
    "region": "delhi",
    "openRank": 904,
    "closeRank": 3824,
    "remarks": ""
  },
  {
    "college": "Tecnia Institute of Advanced Studies, Rohini",
    "course": "BCA",
    "courseGroup": "BCA",
    "shift": "Shift II",
    "category": "GEN",
    "region": "delhi",
    "openRank": 1607,
    "closeRank": 5226,
    "remarks": ""
  },
  {
    "college": "Management Education & Research Institute (MERI), Janakpuri",
    "course": "BCA",
    "courseGroup": "BCA",
    "shift": "Shift I",
    "category": "GEN",
    "region": "delhi",
    "openRank": 1458,
    "closeRank": 3650,
    "remarks": ""
  },
  {
    "college": "New Delhi Institute of Management (NDIM), Tughlakabad",
    "course": "BCA",
    "courseGroup": "BCA",
    "shift": "Morning",
    "category": "GEN",
    "region": "delhi",
    "openRank": 1694,
    "closeRank": 5854,
    "remarks": ""
  },
  {
    "college": "Fairfield Institute of Management & Technology (FIMT), Kapashera",
    "course": "BCA",
    "courseGroup": "BCA",
    "shift": "Shift I",
    "category": "GEN",
    "region": "delhi",
    "openRank": 1790,
    "closeRank": 5745,
    "remarks": ""
  },
  {
    "college": "Ideal Institute of Management & Technology, Vivek Vihar",
    "course": "BCA",
    "courseGroup": "BCA",
    "shift": "Shift I",
    "category": "GEN",
    "region": "delhi",
    "openRank": 1234,
    "closeRank": 5296,
    "remarks": ""
  },
  {
    "college": "Bharatiya Vidya Bhavan, KG Marg",
    "course": "BCA",
    "courseGroup": "BCA",
    "shift": "Morning",
    "category": "GEN",
    "region": "delhi",
    "openRank": 875,
    "closeRank": 4082,
    "remarks": ""
  },
  {
    "college": "Maharaja Surajmal Institute (MSI), Janakpuri",
    "course": "BCA",
    "courseGroup": "BCA",
    "shift": "Shift I",
    "category": "SC",
    "region": "delhi",
    "openRank": 395,
    "closeRank": 4135,
    "remarks": "SC Category"
  },
  {
    "college": "Vivekananda Institute of Professional Studies (VIPS)",
    "course": "BCA",
    "courseGroup": "BCA",
    "shift": "Shift I",
    "category": "SC",
    "region": "delhi",
    "openRank": 2082,
    "closeRank": 4800,
    "remarks": "SC Category"
  },
  {
    "college": "University School of Law & Legal Studies (USLLS), GGSIPU Dwarka",
    "course": "BA-LLB (Hons)",
    "courseGroup": "Law",
    "shift": "Morning",
    "category": "GEN",
    "region": "delhi",
    "openRank": 1224,
    "closeRank": 4031,
    "remarks": "Best Law – Uni campus"
  },
  {
    "college": "University School of Law & Legal Studies (USLLS), GGSIPU Dwarka",
    "course": "BA-LLB (Hons)",
    "courseGroup": "Law",
    "shift": "Morning",
    "category": "GEN",
    "region": "outside_delhi",
    "openRank": 642,
    "closeRank": 2229,
    "remarks": ""
  },
  {
    "college": "University School of Law & Legal Studies (USLLS), GGSIPU Dwarka",
    "course": "BBA-LLB (Hons)",
    "courseGroup": "Law",
    "shift": "Morning",
    "category": "GEN",
    "region": "delhi",
    "openRank": 1775,
    "closeRank": 5049,
    "remarks": ""
  },
  {
    "college": "University School of Law & Legal Studies (USLLS), GGSIPU Dwarka",
    "course": "BBA-LLB (Hons)",
    "courseGroup": "Law",
    "shift": "Morning",
    "category": "GEN",
    "region": "outside_delhi",
    "openRank": 2015,
    "closeRank": 2358,
    "remarks": ""
  },
  {
    "college": "Vivekananda Institute of Professional Studies (VIPS), Pitampura",
    "course": "BA-LLB (Hons)",
    "courseGroup": "Law",
    "shift": "Morning",
    "category": "GEN",
    "region": "delhi",
    "openRank": 1411,
    "closeRank": 15710,
    "remarks": ""
  },
  {
    "college": "Vivekananda Institute of Professional Studies (VIPS), Pitampura",
    "course": "BA-LLB (Hons)",
    "courseGroup": "Law",
    "shift": "Morning",
    "category": "GEN",
    "region": "outside_delhi",
    "openRank": 2004,
    "closeRank": 4396,
    "remarks": ""
  },
  {
    "college": "Vivekananda Institute of Professional Studies (VIPS), Pitampura",
    "course": "BBA-LLB (Hons)",
    "courseGroup": "Law",
    "shift": "Morning",
    "category": "GEN",
    "region": "delhi",
    "openRank": 1563,
    "closeRank": 18947,
    "remarks": ""
  },
  {
    "college": "Vivekananda Institute of Professional Studies (VIPS), Pitampura",
    "course": "BBA-LLB (Hons)",
    "courseGroup": "Law",
    "shift": "Morning",
    "category": "GEN",
    "region": "outside_delhi",
    "openRank": 2437,
    "closeRank": 4804,
    "remarks": ""
  },
  {
    "college": "Maharaja Surajmal Institute (MSI), Janakpuri",
    "course": "BA-LLB (Hons)",
    "courseGroup": "Law",
    "shift": "Morning",
    "category": "GEN",
    "region": "delhi",
    "openRank": 7661,
    "closeRank": 30104,
    "remarks": ""
  },
  {
    "college": "Maharaja Surajmal Institute (MSI), Janakpuri",
    "course": "BBA-LLB (Hons)",
    "courseGroup": "Law",
    "shift": "Morning",
    "category": "GEN",
    "region": "delhi",
    "openRank": 5540,
    "closeRank": 29258,
    "remarks": ""
  },
  {
    "college": "Maharaja Agrasen Institute of Management Studies (MAIMS), Rohini",
    "course": "BA-LLB (Hons)",
    "courseGroup": "Law",
    "shift": "Morning",
    "category": "GEN",
    "region": "delhi",
    "openRank": 4358,
    "closeRank": 36399,
    "remarks": ""
  },
  {
    "college": "Maharaja Agrasen Institute of Management Studies (MAIMS), Rohini",
    "course": "BA-LLB (Hons)",
    "courseGroup": "Law",
    "shift": "Morning",
    "category": "GEN",
    "region": "outside_delhi",
    "openRank": 3737,
    "closeRank": 5136,
    "remarks": ""
  },
  {
    "college": "Maharaja Agrasen Institute of Management Studies (MAIMS), Rohini",
    "course": "BBA-LLB (Hons)",
    "courseGroup": "Law",
    "shift": "Morning",
    "category": "GEN",
    "region": "delhi",
    "openRank": 6714,
    "closeRank": 35054,
    "remarks": ""
  },
  {
    "college": "Maharaja Agrasen Institute of Management Studies (MAIMS), Rohini",
    "course": "BBA-LLB (Hons)",
    "courseGroup": "Law",
    "shift": "Morning",
    "category": "GEN",
    "region": "outside_delhi",
    "openRank": 4415,
    "closeRank": 5856,
    "remarks": ""
  },
  {
    "college": "Gitarattan International Business School (GIBS), Rohini",
    "course": "BA-LLB (Hons)",
    "courseGroup": "Law",
    "shift": "Morning",
    "category": "GEN",
    "region": "delhi",
    "openRank": 6848,
    "closeRank": 8176,
    "remarks": ""
  },
  {
    "college": "Gitarattan International Business School (GIBS), Rohini",
    "course": "BBA-LLB (Hons)",
    "courseGroup": "Law",
    "shift": "Morning",
    "category": "GEN",
    "region": "delhi",
    "openRank": 6898,
    "closeRank": 9230,
    "remarks": ""
  },
  {
    "college": "Trinity Institute of Professional Studies, Dwarka",
    "course": "BA-LLB (Hons)",
    "courseGroup": "Law",
    "shift": "Morning",
    "category": "GEN",
    "region": "delhi",
    "openRank": 5257,
    "closeRank": 46551,
    "remarks": ""
  },
  {
    "college": "Trinity Institute of Professional Studies, Dwarka",
    "course": "BA-LLB (Hons)",
    "courseGroup": "Law",
    "shift": "Morning",
    "category": "GEN",
    "region": "outside_delhi",
    "openRank": 5559,
    "closeRank": 7152,
    "remarks": ""
  },
  {
    "college": "Fairfield Institute of Management & Technology (FIMT), Kapashera",
    "course": "BA-LLB",
    "courseGroup": "Law",
    "shift": "Morning",
    "category": "GEN",
    "region": "delhi",
    "openRank": 6364,
    "closeRank": 11941,
    "remarks": ""
  },
  {
    "college": "Fairfield Institute of Management & Technology (FIMT), Kapashera",
    "course": "BBA-LLB (Hons)",
    "courseGroup": "Law",
    "shift": "Morning",
    "category": "GEN",
    "region": "delhi",
    "openRank": 5936,
    "closeRank": 12551,
    "remarks": ""
  },
  {
    "college": "Ideal Institute of Management & Technology, Vivek Vihar",
    "course": "BA-LLB (Hons)",
    "courseGroup": "Law",
    "shift": "Morning",
    "category": "GEN",
    "region": "delhi",
    "openRank": 6804,
    "closeRank": 11273,
    "remarks": ""
  },
  {
    "college": "Chandarprabhu Jain College, Narela",
    "course": "BA-LLB (Hons)",
    "courseGroup": "Law",
    "shift": "Morning",
    "category": "GEN",
    "region": "delhi",
    "openRank": 9228,
    "closeRank": 13717,
    "remarks": ""
  },
  {
    "college": "Chandarprabhu Jain College, Narela",
    "course": "BBA-LLB (Hons)",
    "courseGroup": "Law",
    "shift": "Morning",
    "category": "GEN",
    "region": "delhi",
    "openRank": 9344,
    "closeRank": 14406,
    "remarks": ""
  },
  {
    "college": "Dr. Akhilesh Das Gupta Institute (ADGIPS), Shastri Park",
    "course": "BA-LLB (Hons)",
    "courseGroup": "Law",
    "shift": "Morning",
    "category": "GEN",
    "region": "delhi",
    "openRank": 12190,
    "closeRank": 14274,
    "remarks": ""
  },
  {
    "college": "Dr. Akhilesh Das Gupta Institute (ADGIPS), Shastri Park",
    "course": "BBA-LLB (Hons)",
    "courseGroup": "Law",
    "shift": "Morning",
    "category": "GEN",
    "region": "delhi",
    "openRank": 10821,
    "closeRank": 15067,
    "remarks": ""
  },
  {
    "college": "University School of Law & Legal Studies (USLLS)",
    "course": "BA-LLB (Hons)",
    "courseGroup": "Law",
    "shift": "Morning",
    "category": "SC",
    "region": "delhi",
    "openRank": 2600,
    "closeRank": 2667,
    "remarks": "SC Category"
  },
  {
    "college": "Maharaja Agrasen Institute of Management Studies (MAIMS)",
    "course": "BA-LLB (Hons)",
    "courseGroup": "Law",
    "shift": "Morning",
    "category": "GEN",
    "region": "outside_delhi",
    "openRank": 15311,
    "closeRank": 28835,
    "remarks": "Ref: Out-Delhi GEN"
  },
  {
    "college": "University School of Management Studies (USMS), GGSIPU Dwarka",
    "course": "B.Com (Hons)",
    "courseGroup": "B.Com",
    "shift": "Morning",
    "category": "GEN",
    "region": "delhi",
    "openRank": 23,
    "closeRank": 347,
    "remarks": "Best B.Com – Uni campus"
  },
  {
    "college": "University School of Management Studies (USMS), GGSIPU Dwarka",
    "course": "B.Com (Hons)",
    "courseGroup": "B.Com",
    "shift": "Morning",
    "category": "GEN",
    "region": "outside_delhi",
    "openRank": 61,
    "closeRank": 213,
    "remarks": ""
  },
  {
    "college": "Vivekananda Institute of Professional Studies (VIPS), Pitampura",
    "course": "B.Com (Hons)",
    "courseGroup": "B.Com",
    "shift": "Shift I",
    "category": "GEN",
    "region": "delhi",
    "openRank": 69,
    "closeRank": 950,
    "remarks": ""
  },
  {
    "college": "Vivekananda Institute of Professional Studies (VIPS), Pitampura",
    "course": "B.Com (Hons)",
    "courseGroup": "B.Com",
    "shift": "Shift II",
    "category": "GEN",
    "region": "delhi",
    "openRank": 123,
    "closeRank": 1570,
    "remarks": ""
  },
  {
    "college": "Vivekananda Institute of Professional Studies (VIPS), Pitampura",
    "course": "B.Com (Hons)",
    "courseGroup": "B.Com",
    "shift": "Shift I",
    "category": "GEN",
    "region": "outside_delhi",
    "openRank": 112,
    "closeRank": 451,
    "remarks": ""
  },
  {
    "college": "Maharaja Agrasen Institute of Management Studies (MAIMS), Rohini",
    "course": "B.Com (Hons)",
    "courseGroup": "B.Com",
    "shift": "Shift I",
    "category": "GEN",
    "region": "delhi",
    "openRank": 3,
    "closeRank": 1406,
    "remarks": ""
  },
  {
    "college": "Maharaja Agrasen Institute of Management Studies (MAIMS), Rohini",
    "course": "B.Com (Hons)",
    "courseGroup": "B.Com",
    "shift": "Shift II",
    "category": "GEN",
    "region": "delhi",
    "openRank": 582,
    "closeRank": 2026,
    "remarks": ""
  },
  {
    "college": "Maharaja Agrasen Institute of Management Studies (MAIMS), Rohini",
    "course": "B.Com (Hons)",
    "courseGroup": "B.Com",
    "shift": "Shift I",
    "category": "GEN",
    "region": "outside_delhi",
    "openRank": 146,
    "closeRank": 714,
    "remarks": ""
  },
  {
    "college": "Maharaja Surajmal Institute (MSI), Janakpuri",
    "course": "B.Com (Hons)",
    "courseGroup": "B.Com",
    "shift": "Shift I",
    "category": "GEN",
    "region": "delhi",
    "openRank": 1,
    "closeRank": 535,
    "remarks": ""
  },
  {
    "college": "Maharaja Surajmal Institute (MSI), Janakpuri",
    "course": "B.Com (Hons)",
    "courseGroup": "B.Com",
    "shift": "Shift II",
    "category": "GEN",
    "region": "delhi",
    "openRank": 262,
    "closeRank": 1267,
    "remarks": ""
  },
  {
    "college": "Maharaja Surajmal Institute (MSI), Janakpuri",
    "course": "B.Com (Hons)",
    "courseGroup": "B.Com",
    "shift": "Shift I",
    "category": "GEN",
    "region": "outside_delhi",
    "openRank": 34,
    "closeRank": 270,
    "remarks": ""
  },
  {
    "college": "Maharaja Surajmal Institute (MSI), Janakpuri",
    "course": "B.Com (Hons)",
    "courseGroup": "B.Com",
    "shift": "Shift II",
    "category": "GEN",
    "region": "outside_delhi",
    "openRank": 179,
    "closeRank": 551,
    "remarks": ""
  },
  {
    "college": "Jagannath International Management School (JIMS), Kalkaji",
    "course": "B.Com (Hons)",
    "courseGroup": "B.Com",
    "shift": "Shift I",
    "category": "GEN",
    "region": "delhi",
    "openRank": 1033,
    "closeRank": 2197,
    "remarks": ""
  },
  {
    "college": "Jagannath International Management School (JIMS), Kalkaji",
    "course": "B.Com (Hons)",
    "courseGroup": "B.Com",
    "shift": "Shift II",
    "category": "GEN",
    "region": "delhi",
    "openRank": 1488,
    "closeRank": 2611,
    "remarks": ""
  },
  {
    "college": "Jagannath International Management School (JIMS), Kalkaji",
    "course": "B.Com (Hons)",
    "courseGroup": "B.Com",
    "shift": "Shift I",
    "category": "GEN",
    "region": "outside_delhi",
    "openRank": 433,
    "closeRank": 858,
    "remarks": ""
  },
  {
    "college": "Institute of Information Technology & Management (IITM), Janakpuri",
    "course": "B.Com (Hons)",
    "courseGroup": "B.Com",
    "shift": "Shift I",
    "category": "GEN",
    "region": "delhi",
    "openRank": 1244,
    "closeRank": 2466,
    "remarks": ""
  },
  {
    "college": "Institute of Information Technology & Management (IITM), Janakpuri",
    "course": "B.Com (Hons)",
    "courseGroup": "B.Com",
    "shift": "Shift II",
    "category": "GEN",
    "region": "delhi",
    "openRank": 2084,
    "closeRank": 3144,
    "remarks": ""
  },
  {
    "college": "Institute of Innovation in Technology & Management (D27), Janakpuri",
    "course": "B.Com (Hons)",
    "courseGroup": "B.Com",
    "shift": "Shift I",
    "category": "GEN",
    "region": "delhi",
    "openRank": 1422,
    "closeRank": 3060,
    "remarks": ""
  },
  {
    "college": "Institute of Innovation in Technology & Management (D27), Janakpuri",
    "course": "B.Com (Hons)",
    "courseGroup": "B.Com",
    "shift": "Shift II",
    "category": "GEN",
    "region": "delhi",
    "openRank": 3158,
    "closeRank": 3605,
    "remarks": ""
  },
  {
    "college": "JIMS Engineering Management Technical Campus, Greater Noida",
    "course": "B.Com (Hons)",
    "courseGroup": "B.Com",
    "shift": "Morning",
    "category": "GEN",
    "region": "outside_delhi",
    "openRank": 507,
    "closeRank": 1512,
    "remarks": "NCR campus"
  },
  {
    "college": "Rukmini Devi Institute of Advanced Studies (RDIAS), Rohini",
    "course": "B.Com (Hons)",
    "courseGroup": "B.Com",
    "shift": "Morning",
    "category": "GEN",
    "region": "delhi",
    "openRank": 1544,
    "closeRank": 3668,
    "remarks": ""
  },
  {
    "college": "Delhi School of Professional Studies & Research (DSPSR), Rohini",
    "course": "B.Com (Hons)",
    "courseGroup": "B.Com",
    "shift": "Shift I",
    "category": "GEN",
    "region": "delhi",
    "openRank": 2796,
    "closeRank": 4310,
    "remarks": ""
  },
  {
    "college": "Guru Nanak Institute of Management (Minority), Punjabi Bagh",
    "course": "B.Com (Hons)",
    "courseGroup": "B.Com",
    "shift": "Shift I",
    "category": "GEN",
    "region": "delhi",
    "openRank": 2827,
    "closeRank": 6734,
    "remarks": "Sikh Minority Institute"
  },
  {
    "college": "Fairfield Institute of Management & Technology (FIMT)",
    "course": "B.Com (Hons)",
    "courseGroup": "B.Com",
    "shift": "Shift I",
    "category": "GEN",
    "region": "delhi",
    "openRank": 3075,
    "closeRank": 3974,
    "remarks": ""
  },
  {
    "college": "Bharatiya Vidya Bhavan, KG Marg",
    "course": "B.Com (Hons)",
    "courseGroup": "B.Com",
    "shift": "Morning",
    "category": "GEN",
    "region": "delhi",
    "openRank": 1841,
    "closeRank": 4340,
    "remarks": ""
  },
  {
    "college": "Don Bosco Institute of Technology, Okhla",
    "course": "B.Com (Hons)",
    "courseGroup": "B.Com",
    "shift": "Morning",
    "category": "GEN",
    "region": "delhi",
    "openRank": 1816,
    "closeRank": 4609,
    "remarks": ""
  },
  {
    "college": "Delhi Institute of Advanced Studies (DIAS), Rohini",
    "course": "B.Com (Hons)",
    "courseGroup": "B.Com",
    "shift": "Morning",
    "category": "GEN",
    "region": "delhi",
    "openRank": 2983,
    "closeRank": 2983,
    "remarks": ""
  },
  {
    "college": "Trinity Institute of Professional Studies, Dwarka",
    "course": "B.Com (Hons)",
    "courseGroup": "B.Com",
    "shift": "Shift I",
    "category": "GEN",
    "region": "delhi",
    "openRank": 1941,
    "closeRank": 3243,
    "remarks": ""
  },
  {
    "college": "Maharaja Surajmal Institute (MSI), Janakpuri",
    "course": "B.Com (Hons)",
    "courseGroup": "B.Com",
    "shift": "Shift I",
    "category": "SC",
    "region": "delhi",
    "openRank": 1216,
    "closeRank": 7855,
    "remarks": "SC Category"
  },
  {
    "college": "Maharaja Agrasen Institute of Management Studies (MAIMS)",
    "course": "B.Com (Hons)",
    "courseGroup": "B.Com",
    "shift": "Shift I",
    "category": "SC",
    "region": "delhi",
    "openRank": 3376,
    "closeRank": 4937,
    "remarks": "SC Category"
  },
  {
    "college": "University School of Information & Communication Technology (USICT), GGSIPU",
    "course": "MCA (Software Engineering)",
    "courseGroup": "MCA",
    "shift": "Morning",
    "category": "GEN",
    "region": "delhi",
    "openRank": 795,
    "closeRank": 2758,
    "remarks": "Best MCA – Uni campus"
  },
  {
    "college": "University School of Information & Communication Technology (USICT), GGSIPU",
    "course": "MCA (Software Engineering)",
    "courseGroup": "MCA",
    "shift": "Morning",
    "category": "GEN",
    "region": "outside_delhi",
    "openRank": 311,
    "closeRank": 980,
    "remarks": ""
  },
  {
    "college": "Vivekananda Institute of Professional Studies (VIPS-TC), Pitampura",
    "course": "MCA",
    "courseGroup": "MCA",
    "shift": "Morning",
    "category": "GEN",
    "region": "delhi",
    "openRank": 3334,
    "closeRank": 11073,
    "remarks": ""
  },
  {
    "college": "Vivekananda Institute of Professional Studies (VIPS-TC), Pitampura",
    "course": "MCA",
    "courseGroup": "MCA",
    "shift": "Morning",
    "category": "GEN",
    "region": "outside_delhi",
    "openRank": 1928,
    "closeRank": 10396,
    "remarks": ""
  },
  {
    "college": "Jagan Institute of Management Studies (JIMS), Rohini Sector-5",
    "course": "MCA",
    "courseGroup": "MCA",
    "shift": "Shift I",
    "category": "GEN",
    "region": "delhi",
    "openRank": 4336,
    "closeRank": 12116,
    "remarks": ""
  },
  {
    "college": "Jagan Institute of Management Studies (JIMS), Rohini Sector-5",
    "course": "MCA",
    "courseGroup": "MCA",
    "shift": "Shift II",
    "category": "GEN",
    "region": "delhi",
    "openRank": 5393,
    "closeRank": 11846,
    "remarks": ""
  },
  {
    "college": "Jagan Institute of Management Studies (JIMS), Rohini Sector-5",
    "course": "MCA",
    "courseGroup": "MCA",
    "shift": "Shift I",
    "category": "GEN",
    "region": "outside_delhi",
    "openRank": 1726,
    "closeRank": 10050,
    "remarks": ""
  },
  {
    "college": "Banarsidas Chandiwala Institute of Information Technology (BCIIT), Kalkaji",
    "course": "MCA",
    "courseGroup": "MCA",
    "shift": "Morning",
    "category": "GEN",
    "region": "delhi",
    "openRank": 2396,
    "closeRank": 9856,
    "remarks": ""
  },
  {
    "college": "Bharti Vidyapeeth Institute of Computer Applications (BVICAM), Paschim Vihar",
    "course": "MCA",
    "courseGroup": "MCA",
    "shift": "Morning",
    "category": "GEN",
    "region": "delhi",
    "openRank": 1387,
    "closeRank": 6383,
    "remarks": ""
  },
  {
    "college": "Bharti Vidyapeeth Institute of Computer Applications (BVICAM), Paschim Vihar",
    "course": "MCA",
    "courseGroup": "MCA",
    "shift": "Morning",
    "category": "GEN",
    "region": "outside_delhi",
    "openRank": 1027,
    "closeRank": 1419,
    "remarks": ""
  },
  {
    "college": "C-DAC, Sector-62, Noida",
    "course": "MCA",
    "courseGroup": "MCA",
    "shift": "Morning",
    "category": "GEN",
    "region": "delhi",
    "openRank": 1033,
    "closeRank": 5135,
    "remarks": "Govt undertaking"
  },
  {
    "college": "C-DAC, Sector-62, Noida",
    "course": "MCA",
    "courseGroup": "MCA",
    "shift": "Morning",
    "category": "GEN",
    "region": "outside_delhi",
    "openRank": 885,
    "closeRank": 1080,
    "remarks": ""
  },
  {
    "college": "Institute of Information Technology & Management (IITM), Janakpuri",
    "course": "MCA",
    "courseGroup": "MCA",
    "shift": "Morning",
    "category": "GEN",
    "region": "delhi",
    "openRank": 5243,
    "closeRank": 11955,
    "remarks": ""
  },
  {
    "college": "Institute of Information Technology & Management (IITM), Janakpuri",
    "course": "MCA",
    "courseGroup": "MCA",
    "shift": "Morning",
    "category": "GEN",
    "region": "outside_delhi",
    "openRank": 2013,
    "closeRank": 6230,
    "remarks": ""
  },
  {
    "college": "Tecnia Institute of Advanced Studies, Rohini",
    "course": "MCA",
    "courseGroup": "MCA",
    "shift": "Morning",
    "category": "GEN",
    "region": "delhi",
    "openRank": 10354,
    "closeRank": 11948,
    "remarks": ""
  },
  {
    "college": "Don Bosco Institute of Technology, Okhla",
    "course": "MCA",
    "courseGroup": "MCA",
    "shift": "Morning",
    "category": "GEN",
    "region": "delhi",
    "openRank": 5452,
    "closeRank": 11262,
    "remarks": ""
  },
  {
    "college": "University School of Management Studies (USMS), GGSIPU Dwarka",
    "course": "MBA",
    "courseGroup": "MBA",
    "shift": "Morning",
    "category": "GEN",
    "region": "delhi",
    "openRank": 1,
    "closeRank": 178,
    "remarks": "Best MBA in IPU; rank = CET rank"
  },
  {
    "college": "Jagan Institute of Management Studies (JIMS), Rohini",
    "course": "MBA",
    "courseGroup": "MBA",
    "shift": "Morning",
    "category": "GEN",
    "region": "delhi",
    "openRank": 200,
    "closeRank": 2000,
    "remarks": "NAAC A grade"
  },
  {
    "college": "Maharaja Surajmal Institute (MSI), Janakpuri",
    "course": "MBA",
    "courseGroup": "MBA",
    "shift": "Morning",
    "category": "GEN",
    "region": "delhi",
    "openRank": 300,
    "closeRank": 3500,
    "remarks": ""
  },
  {
    "college": "New Delhi Institute of Management (NDIM), Tughlakabad",
    "course": "MBA",
    "courseGroup": "MBA",
    "shift": "Morning",
    "category": "GEN",
    "region": "delhi",
    "openRank": 400,
    "closeRank": 4500,
    "remarks": ""
  },
  {
    "college": "Maharaja Agrasen Institute of Management Studies (MAIMS)",
    "course": "MBA",
    "courseGroup": "MBA",
    "shift": "Morning",
    "category": "GEN",
    "region": "delhi",
    "openRank": 600,
    "closeRank": 5500,
    "remarks": ""
  },
  {
    "college": "Rukmini Devi Institute of Advanced Studies (RDIAS)",
    "course": "MBA",
    "courseGroup": "MBA",
    "shift": "Morning",
    "category": "GEN",
    "region": "delhi",
    "openRank": 1500,
    "closeRank": 8000,
    "remarks": ""
  },
  {
    "college": "Gitarattan International Business School (GIBS)",
    "course": "MBA",
    "courseGroup": "MBA",
    "shift": "Morning",
    "category": "GEN",
    "region": "delhi",
    "openRank": 2000,
    "closeRank": 10000,
    "remarks": ""
  },
  {
    "college": "Trinity Institute of Professional Studies, Dwarka",
    "course": "MBA",
    "courseGroup": "MBA",
    "shift": "Morning",
    "category": "GEN",
    "region": "delhi",
    "openRank": 2500,
    "closeRank": 12000,
    "remarks": ""
  }
];
